<<<<<<< HEAD
import google.generativeai as genai
=======
"""
Vercel Serverless Function: AI Text Detection
Endpoint: POST /api/detect
Uses Google Gemini API
"""

from http.server import BaseHTTPRequestHandler
>>>>>>> ee328d5 (Initial commit)
import json
import os
import google.generativeai as genai
import re

<<<<<<< HEAD
genai.configure(api_key=os.environ["GEMINI_API_KEY"])

def handler(request):
    try:
        body = request.get_json()
        text = body.get("text", "")

        model = genai.GenerativeModel("gemini-pro")

        prompt = f"""
        Analyze the following text and estimate the probability (0 to 100) that 
        it was generated by AI. Respond ONLY with a number.

        Text:
        {text}
        """

        response = model.generate_content(prompt)
        score = response.text.strip()

        return {
            "statusCode": 200,
            "headers": {"Content-Type": "application/json"},
            "body": json.dumps({"ai_score": score})
        }

    except Exception as e:
        return {
            "statusCode": 500,
            "body": json.dumps({"error": str(e)})
        }
=======
# Configure Gemini API
genai.configure(api_key=os.environ.get("GEMINI_API_KEY"))

class handler(BaseHTTPRequestHandler):
    """Vercel serverless function handler"""
    
    def do_OPTIONS(self):
        """Handle CORS preflight requests"""
        self.send_response(200)
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        self.end_headers()
    
    def do_POST(self):
        """Handle POST requests for AI text detection"""
        # Set response headers with CORS
        self.send_response(200)
        self.send_header('Content-type', 'application/json')
        self.send_header('Access-Control-Allow-Origin', '*')
        self.send_header('Access-Control-Allow-Methods', 'POST, OPTIONS')
        self.send_header('Access-Control-Allow-Headers', 'Content-Type')
        self.end_headers()
        
        try:
            # Read request body
            content_length = int(self.headers.get('Content-Length', 0))
            if content_length == 0:
                response = {"error": "Empty request body"}
                self.wfile.write(json.dumps(response).encode())
                return
            
            post_data = self.rfile.read(content_length)
            data = json.loads(post_data.decode('utf-8'))
            
            text = data.get('text', '').strip()
            
            if not text:
                response = {"error": "No text provided"}
                self.wfile.write(json.dumps(response).encode())
                return
            
            if len(text) < 50:
                response = {"error": "Text must be at least 50 characters"}
                self.wfile.write(json.dumps(response).encode())
                return
            
            # Build detection prompt
            prompt = f"""Analyze the following text and determine if it was generated by AI or written by a human. 
Provide your analysis in the following format:

VERDICT: [AI or HUMAN]
CONFIDENCE: [percentage as number]
AI_PROBABILITY: [percentage as number]
HUMAN_PROBABILITY: [percentage as number]
INDICATORS: [comma-separated list of key indicators]
STYLE_ANALYSIS: [brief analysis of writing style]

Text to analyze:
{text}

Analysis:"""
            
            # Generate detection using Gemini
            print(f"Analyzing text: {len(text)} characters")
            model = genai.GenerativeModel("gemini-pro")
            gemini_response = model.generate_content(prompt)
            
            analysis_text = gemini_response.text.strip()
            
            # Parse the response
            result = self.parse_detection_response(analysis_text, text)
            
            # Return result
            self.wfile.write(json.dumps(result).encode())
            print("✅ Detection complete!")
            
        except json.JSONDecodeError:
            error_response = {"error": "Invalid JSON format"}
            self.wfile.write(json.dumps(error_response).encode())
            print("❌ JSON decode error")
        except Exception as e:
            error_response = {"error": f"Internal error: {str(e)}"}
            self.wfile.write(json.dumps(error_response).encode())
            print(f"❌ Error: {str(e)}")
    
    def parse_detection_response(self, analysis_text, original_text):
        """Parse Gemini's response into structured format"""
        # Initialize default values
        is_ai = False
        confidence = "Medium"
        ai_probability = 50
        human_probability = 50
        indicators = []
        style_analysis = ""
        
        # Try to extract structured data
        verdict_match = re.search(r'VERDICT:\s*(AI|HUMAN)', analysis_text, re.IGNORECASE)
        if verdict_match:
            is_ai = verdict_match.group(1).upper() == 'AI'
        
        confidence_match = re.search(r'CONFIDENCE:\s*(\d+)', analysis_text, re.IGNORECASE)
        if confidence_match:
            conf_num = int(confidence_match.group(1))
            if conf_num >= 80:
                confidence = "Very High"
            elif conf_num >= 60:
                confidence = "High"
            elif conf_num >= 40:
                confidence = "Medium"
            else:
                confidence = "Low"
        
        ai_prob_match = re.search(r'AI_PROBABILITY:\s*(\d+)', analysis_text, re.IGNORECASE)
        if ai_prob_match:
            ai_probability = int(ai_prob_match.group(1))
            human_probability = 100 - ai_probability
        
        indicators_match = re.search(r'INDICATORS:\s*([^\n]+)', analysis_text, re.IGNORECASE)
        if indicators_match:
            indicators_str = indicators_match.group(1).strip()
            indicators = [ind.strip() for ind in indicators_str.split(',') if ind.strip()]
        
        style_match = re.search(r'STYLE_ANALYSIS:\s*([^\n]+(?:\n[^\n]+)*)', analysis_text, re.IGNORECASE)
        if style_match:
            style_analysis = style_match.group(1).strip()
        
        # If parsing failed, use the full analysis text as style analysis
        if not style_analysis:
            style_analysis = analysis_text[:500]  # Limit length
        
        # If no indicators found, add default ones
        if not indicators:
            indicators = ["Analysis completed", "Review the style analysis for details"]
        
        # Calculate word count
        word_count = len(original_text.split())
        
        return {
            "success": True,
            "isAI": is_ai,
            "confidence": confidence,
            "aiProbability": ai_probability,
            "humanProbability": human_probability,
            "indicators": indicators,
            "styleAnalysis": style_analysis,
            "wordCount": word_count
        }
>>>>>>> ee328d5 (Initial commit)
