import google.generativeai as genai
import json
import os

genai.configure(api_key=os.environ["GEMINI_API_KEY"])

def handler(request):
    try:
        body = request.get_json()
        text = body.get("text", "")

        model = genai.GenerativeModel("gemini-pro")

        prompt = f"""
        Analyze the following text and estimate the probability (0 to 100) that 
        it was generated by AI. Respond ONLY with a number.

        Text:
        {text}
        """

        response = model.generate_content(prompt)
        score = response.text.strip()

        return {
            "statusCode": 200,
            "headers": {"Content-Type": "application/json"},
            "body": json.dumps({"ai_score": score})
        }

    except Exception as e:
        return {
            "statusCode": 500,
            "body": json.dumps({"error": str(e)})
        }
