"""
Vercel Serverless Function: AI Text Detection
Endpoint: POST /api/detect
Uses Google Gemini API
"""

import json
import os
import google.generativeai as genai
import re

# Configure Gemini API
genai.configure(api_key=os.environ.get("GEMINI_API_KEY"))

def handler(request):
    """Vercel serverless function handler"""
    try:
        # Handle CORS preflight
        if request.method == 'OPTIONS':
            return {
                "statusCode": 200,
                "headers": {
                    "Content-Type": "application/json",
                    "Access-Control-Allow-Origin": "*",
                    "Access-Control-Allow-Methods": "POST, OPTIONS",
                    "Access-Control-Allow-Headers": "Content-Type"
                },
                "body": json.dumps({})
            }
        
        # Parse request body - Vercel Python format
        body = {}
        if hasattr(request, 'body'):
            if isinstance(request.body, bytes):
                body = json.loads(request.body.decode('utf-8'))
            elif isinstance(request.body, str):
                body = json.loads(request.body)
        elif hasattr(request, 'get_json'):
            try:
                body = request.get_json()
            except:
                body = {}
        
        if not body:
            return {
                "statusCode": 400,
                "headers": {
                    "Content-Type": "application/json",
                    "Access-Control-Allow-Origin": "*"
                },
                "body": json.dumps({"error": "Empty request body"})
            }
        
        text = body.get('text', '').strip()
        
        if not text:
            return {
                "statusCode": 400,
                "headers": {
                    "Content-Type": "application/json",
                    "Access-Control-Allow-Origin": "*"
                },
                "body": json.dumps({"error": "No text provided"})
            }
        
        if len(text) < 50:
            return {
                "statusCode": 400,
                "headers": {
                    "Content-Type": "application/json",
                    "Access-Control-Allow-Origin": "*"
                },
                "body": json.dumps({"error": "Text must be at least 50 characters"})
            }
        
        # Build detection prompt
        prompt = f"""Analyze the following text and determine if it was generated by AI or written by a human. 
Provide your analysis in the following format:

VERDICT: [AI or HUMAN]
CONFIDENCE: [percentage as number]
AI_PROBABILITY: [percentage as number]
HUMAN_PROBABILITY: [percentage as number]
INDICATORS: [comma-separated list of key indicators]
STYLE_ANALYSIS: [brief analysis of writing style]

Text to analyze:
{text}

Analysis:"""
        
        # Generate detection using Gemini
        print(f"Analyzing text: {len(text)} characters")
        model = genai.GenerativeModel("gemini-pro")
        gemini_response = model.generate_content(prompt)
        
        analysis_text = gemini_response.text.strip()
        
        # Parse the response
        result = parse_detection_response(analysis_text, text)
        
        # Return result
        return {
            "statusCode": 200,
            "headers": {
                "Content-Type": "application/json",
                "Access-Control-Allow-Origin": "*"
            },
            "body": json.dumps(result)
        }
        
    except json.JSONDecodeError as e:
        return {
            "statusCode": 400,
            "headers": {
                "Content-Type": "application/json",
                "Access-Control-Allow-Origin": "*"
            },
            "body": json.dumps({"error": f"Invalid JSON format: {str(e)}"})
        }
        except Exception as e:
        print(f"❌ Error: {str(e)}")
        import traceback
        print(traceback.format_exc())
        return {
            "statusCode": 500,
            "headers": {
                "Content-Type": "application/json",
                "Access-Control-Allow-Origin": "*"
            },
            "body": json.dumps({"error": f"Internal error: {str(e)}"})
        }

def parse_detection_response(analysis_text, original_text):
    """Parse Gemini's response into structured format"""
    # Initialize default values
    is_ai = False
    confidence = "Medium"
    ai_probability = 50
    human_probability = 50
    indicators = []
    style_analysis = ""
    
    # Try to extract structured data
    verdict_match = re.search(r'VERDICT:\s*(AI|HUMAN)', analysis_text, re.IGNORECASE)
    if verdict_match:
        is_ai = verdict_match.group(1).upper() == 'AI'
    
    confidence_match = re.search(r'CONFIDENCE:\s*(\d+)', analysis_text, re.IGNORECASE)
    if confidence_match:
        conf_num = int(confidence_match.group(1))
        if conf_num >= 80:
            confidence = "Very High"
        elif conf_num >= 60:
            confidence = "High"
        elif conf_num >= 40:
            confidence = "Medium"
        else:
            confidence = "Low"
    
    ai_prob_match = re.search(r'AI_PROBABILITY:\s*(\d+)', analysis_text, re.IGNORECASE)
    if ai_prob_match:
        ai_probability = int(ai_prob_match.group(1))
        human_probability = 100 - ai_probability
    
    indicators_match = re.search(r'INDICATORS:\s*([^\n]+)', analysis_text, re.IGNORECASE)
    if indicators_match:
        indicators_str = indicators_match.group(1).strip()
        indicators = [ind.strip() for ind in indicators_str.split(',') if ind.strip()]
    
    style_match = re.search(r'STYLE_ANALYSIS:\s*([^\n]+(?:\n[^\n]+)*)', analysis_text, re.IGNORECASE)
    if style_match:
        style_analysis = style_match.group(1).strip()
    
    # If parsing failed, use the full analysis text as style analysis
    if not style_analysis:
        style_analysis = analysis_text[:500]  # Limit length
    
    # If no indicators found, add default ones
    if not indicators:
        indicators = ["Analysis completed", "Review the style analysis for details"]
    
    # Calculate word count
    word_count = len(original_text.split())
    
    return {
        "success": True,
        "isAI": is_ai,
        "confidence": confidence,
        "aiProbability": ai_probability,
        "humanProbability": human_probability,
        "indicators": indicators,
        "styleAnalysis": style_analysis,
        "wordCount": word_count
    }
